# Default values for amplication.
# This is a YAML-formatted file.
name: scheduler

deployment:
  replicaCount: 1
  volume:
    enabled: false
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  image:
    pullPolicy: Always
    repository: amplication/scheduler
    tag: latest
    imagePullSecrets: []
  
  command:
    enabled: true
  securityContext:
    enabled: false

service:
  enabled: false
  app_port_number: 3000
  app_name: app

traefik:
  enabled: false

config:
  enabled: true
  env:
    POSTGRESQL_URL: "postgres://postgres:Fd7zZXWvCY3bdgLHz@postgres:5432"

pvc:
  enabled: false

job:
  enabled: false

# Postgresql Server
postgres:
  install: false
