{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Chart.Name }}-{{ .Values.name }}'
data:
  {{- range $key, $val := .Values.config.env }}
    {{ $key }}: {{ $val }}
  {{- end }}
{{- end }}