{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.name }}-migrate"
spec:
  template:
    metadata:
      name: "{{ .Values.name }}-migrate"
    spec:
      restartPolicy: Never
      initContainers:
      {{ if .Values.postgres.install }}
      - name: wait-for-postgres-connection
        image: {{ .Values.postgres.image }}
        imagePullPolicy: {{ .Values.postgres.imagePullPolicy }}
        args:
          - "pod"
          - "{{ .Release.Name }}-postgresql-0"
      {{ end }}
      containers:
      - name: "{{ .Values.name }}-migrate"
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        command: ["/bin/sh"]
        args: ["-c", "npm run migrate:up"]
        env:
        - name: POSTGRESQL_URL
          value: "postgres://postgres:{{ .Values.global.postgresql.postgresqlPassword }}@{{ .Release.Name }}-postgresql:5432"
{{- end }}