---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 'migration-{{ .Values.name }}'
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'migration-{{ .Values.name }}'
  namespace: {{ .Values.environment }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.environment }}
roleRef:
  kind: Role
  name: 'migration-{{ .Values.name }}'
  apiGroup: rbac.authorization.k8s.io
