{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Chart.Name }}-{{ .Values.name }}'
  labels:
    app: '{{ .Chart.Name }}-{{ .Values.name }}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.port.name }}
      port: {{ .Values.service.port.number }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: '{{ .Chart.Name }}-{{ .Values.name }}'
{{- end }}