name: Deploy To Staging OC

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

#      - name: "Build and push amplication/amplication Docker image"
#        uses: docker/build-push-action@v2
#        with:
#          pull: true
#          push: true
#          cache-from: type=local,src=/tmp/.buildx-cache
#          cache-to: type=local,dest=/tmp/.buildx-cache
#          tags: |
#            gcr.io/amplication-staging-oc/amplication:${{ github.sha }}

      - uses: hashicorp/setup-terraform@v1

      - run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        working-directory: terraform/envs/staging-oc

      - run: terraform apply -auto-approve -lock-timeout=1200s
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_image_id: gcr.io/amplication-staging-oc/amplication@sha256:a9b38a77a91a9f2f800116a41b2a4387720719ec0f242f54013bbaa668d1af89
          TF_VAR_github_app_private_key: ${{ secrets.STAGING_GITHUB_APP_PRIVATE_KEY }}
          TF_VAR_github_app_client_secret: ${{ secrets.STAGING_GITHUB_APP_CLIENT_SECRET }}
          TF_VAR_db_url: ${{ secrets.AWS_PROD_POSTGRESQL_URL_PLAINTEXT }}
        working-directory: terraform/envs/staging-oc

      - uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GOOGLE_CREDENTIALS }}
          instance: ${{ secrets.STAGING_DB_INSTANCE_NAME }}

      - run: |
          set -e;
          docker run \
            --network host \
            --env POSTGRESQL_URL="${{ secrets.AWS_PROD_POSTGRESQL_URL_PLAINTEXT }}/amplication" \
            gcr.io/amplication-staging-oc/amplication@sha256:a9b38a77a91a9f2f800116a41b2a4387720719ec0f242f54013bbaa668d1af89 \
            npm run migrate:up
